#!/bin/sh /etc/rc.common
START=94
STOP=11
USE_PROCD=1

start_service() {
	for conf in /var/run/csqtt/dns-*.conf; do
		[ -f "$conf" ] || continue
		name=${conf##*/dns-}; name=${name%.conf}
		case "$name" in ''|*[!a-zA-Z0-9_]*) continue ;; esac
		procd_open_instance "dns_$name"
		procd_set_param command /usr/sbin/dnsmasq --keep-in-foreground "--conf-file=$conf"
		procd_set_param respawn 3600 2 0
		procd_set_param file "$conf"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	done
}
