include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI interface for CSQTT
LUCI_DEPENDS:=+csqtt +luci-base +rpcd
LUCI_PKGARCH:=all
PKG_LICENSE:=PolyForm-Noncommercial-1.0.0
PKG_MAINTAINER:=CSQTT OpenWrt contributors

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
